apiVersion: v1
kind: Template
metadata:
  name: cerebro-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: openshift-cerebro
    name: openshift-cerebro
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: openshift-cerebro:latest
    source:
      git:
        uri: ${BUILD_REPO_URI}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: centos:centos7
      type: Docker
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: openshift-cerebro
    name: openshift-cerebro
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      component: cerebro
      deploymentconfig: cerebro
      logging-infra: cerebro
      provider: openshift
    name: cerebro
  spec:
    ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      component: cerebro
      deploymentconfig: cerebro
      logging-infra: cerebro
      provider: openshift
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      component: cerebro
      deploymentconfig: cerebro
      logging-infra: cerebro
      provider: openshift
    name: cerebro
  spec:
    port:
      targetPort: 9000
    to:
      kind: Service
      name: cerebro
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      component: cerebro
      logging-infra: cerebro
      provider: openshift
    name: cerebro
  spec:
    replicas: 1
    selector:
      component: cerebro
      logging-infra: cerebro
      provider: openshift
    strategy:
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: cerebro
          logging-infra: cerebro
          provider: openshift
        name: cerebro
      spec:
        containers:
        - env:
          - name: ES_CLUSTER_ADDRESS
            value: ${ELASTICSEARCH_CLUSTER_ADDRESS}
          image: ${IMAGE_PREFIX}:${IMAGE_VERSION}
          imagePullPolicy: Always
          name: cerebro
          ports:
          - containerPort: 9000
            name: restapi
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/cerebro/secrets
            name: es-secrets
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext:
          supplementalGroups:
          - 65534
        serviceAccountName: ${SA_NAME}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: es-secrets
          secret:
            defaultMode: 420
            secretName: ${SECRETS_NAME}
    test: false
    triggers:
    - type: ConfigChange
parameters:
- name: IMAGE_PREFIX
  value: "phlbrz/openshift-cerebro"
  required: true
- name: IMAGE_VERSION
  value: "latest"
  required: true
- name: SA_NAME
  value: "aggregated-logging-elasticsearch"
  required: true
- name: SECRETS_NAME
  value: "logging-elasticsearch"
  required: true
- name: BUILD_REPO_URI
  value: "https://github.com/phlbrz/openshift-cerebro"
  required: true
- name: ELASTICSEARCH_CLUSTER_ADDRESS
  value: "logging-es"
  required: true
